### ISSUE TITLE
Feature Request : Finder Label Color Check / SET

### ISSUE THREAD

**Issue by chrisondrovic** [benjaminoakes/maid#125]
Would really like to have the ability to check the finder label color of a file and also have the ability to set it

**Comment by songchenwen** [comment]
[Here is my config file](https://github.com/songchenwen/dotfiles/blob/master/maid_rules/rules.rb).

I use [this little command](https://github.com/jdberry/tag/) to handle Finder labels. 

I'd like to submit a pull request for this. I just need to know what is the best way to embed a binary in maid.

**Comment by benjaminoakes** [comment]
@songchenwen That looks really interesting...

I have a few guidelines:

* Any solution must work on Linux.  By that, I mean `maid` can't fail to install just because of OSX specific code existing to support the OSX-only tagging feature.  To be clear, we **don't** need to have the exact same featureset on Linux.
* From looking at jdberry/tag, it seems like a Ruby gem that wraps it could be a very good idea.  I don't know much about taking that approach, but looking at `rb-fsevent` could be a good starting point.

**Comment by benjaminoakes** [comment]
@songchenwen I was thinking about this recently... how about we just assume they have `tag` installed?  If they don't, we'll give them a download link.

I'll have some time to do a release on Sunday if you have a chance to make a pull request with the code from your config file.  I'd like to have you receive the recognition you deserve!  (vs. me copying and pasting, in which case it would look like I wrote it)

**Comment by songchenwen** [comment]
Ok. I'll try to make a PR before Sunday. 

To make things clear, do I just need to add these methods to `tools.rb`? And what should we suggest when Linux user try to use these methods?

**Comment by benjaminoakes** [comment]
Awesome, thank you!

Adding to `tools.rb` is the only requirement, but specs would be appreciated of course if you have time.  Also, there's a lot of great stuff in your `rules.rb` besides the "tag" code.  All of the utility methods you wrote would be welcome.

As for Linux users, I think we can just report that tagging isn't available since it's an OSX-only feature.  The `Maid::Platform.osx?` command is available to check what platform `maid` is running on.

In pseudo code:

```
if Maid::Platform.osx?
  if has_tag_available?
    cmd(...)
  else
    print "To use this feature, you need `tag` installed.  Run `brew install tag`"
  end
else
  print "sorry, tagging is unavailable on your platform"
end
```

**Comment by songchenwen** [comment]
I'm not that much a ruby guy. But I'll try my best. :smile:
