### ISSUE TITLE
Requiring `--force` breaks with Unix convention

### ISSUE THREAD

**Issue by brandondrew** [benjaminoakes/maid#140]
It is normal across Unix shell utilities for `--force` to only be required in extreme circumstances, when you would normally have reason to *not* run the utility.   So it's very unconventional to require `--force` just to *actually make any changes at all*.  I think a better scheme might be like so:

* if `--force` is used then go ahead and make the changes (as it is right now)
* if `--force` is *not* used, then prompt the user for each change individually (or in small batches, like one batch per rule).  maid could list all the things it would do for a given rule (just as it does with `--dry-run`) and then ask the user if this is what they'd like done.  The user could say yes to the whole lot of the changes for that rule, or could step through one-by-one.

This would preserve the value of requiring `--force`, while at the same time providing an interface that made sense to people accustomed to Unix commandline utilities.

**Comment by benjaminoakes** [comment]
While what you say about convention is true, `--force` was chosen for Maid to act more like `git clean`.  Check out this thread on Hacker News for context: https://news.ycombinator.com/item?id=4929243

That said, what you suggest could be a good compromise if others agree. However, since it changes the meaning of a command, this behavior wouldn't become default until a major version change (e.g. v1.0, per semver conventions).

If this were added as a new command such as `maid ask` or `maid prompt`, we could try out the idea before making it default.
