### ISSUE TITLE
non-latin character in rules.rb doesn't seem to work

### ISSUE THREAD

**Issue by Canorus** [benjaminoakes/maid#166]
as mentioned in title, when file name contains non-latin character(perhaps ascii) maid doesn't seem to work.

code goes like below

```
rule 'Screenshots' do
	dir('~/Pictures/screencapture/스크린샷 *').each do |path|
		move(path, '~/Desktop/screenshots_new/')
	end
end
```

that is, trying to move all screenshot files to new location`screenshot_new` but it doesn’t work. Am I doing anything wrong?

hope I'm asking at right place…

**Comment by benjaminoakes** [comment]
It's possible that this is broken, though there is [a test file for this case](https://github.com/benjaminoakes/maid/blob/master/spec/fixtures/files/%E3%81%95.zip) that should catch this problem.

I'm assuming this issue was closed because this turned out not to be the problem, but please re-open if you've found something.  Thanks for using maid.  :smile:

**Comment by Canorus** [comment]
To be honest, at the time I closed this issue, I thought this repository is not maintained anymore.

As I continued other personal projects, I encountered some similar symptoms and it turns out, **macOS(and iOS) would not normalize unicode character on OS level** while Windows do. This may cause problem with not only Korean but also Greek, Arabic, Hebrew characters. For those of you that's having similar problem, please check [this page](http://unicode.org/faq/normalization.html)

Hopefully there seems a number of conversion library, and those might help I presume.

p.s. thank you **SO** much for making and maintaining maid. I had 1000+ files in my download folders and maid helped **A LOT** cleaning up.
